# Generated by Django 3.0.3 on 2020-07-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordermodel',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='orderroutemodel',
            name='routes',
            field=models.TextField(blank=True, verbose_name='物流过程'),
        ),
    ]
