# Generated by Django 3.0.3 on 2020-12-24 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200706_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='refund_number',
            field=models.CharField(default=0, max_length=64, verbose_name='退款订单'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='refund_reason',
            field=models.TextField(blank=True, verbose_name='收货人备注'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='flags',
            field=models.SmallIntegerField(choices=[(0, '未付款'), (1, '已付款'), (2, '配送中'), (3, '已签收'), (4, '已取消'), (5, '退款中'), (6, '已退款')], default=0, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='ordershistorymodel',
            name='flags',
            field=models.SmallIntegerField(choices=[(0, '未付款'), (1, '已付款'), (2, '配送中'), (3, '已签收'), (4, '已取消'), (5, '已退款'), (6, '请求退款')], default=0),
        ),
    ]
