# Generated by Django 3.0.3 on 2020-12-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20201224_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='refund_number',
            field=models.CharField(blank=True, max_length=64, verbose_name='退款订单'),
        ),
        migrations.AlterField(
            model_name='ordershistorymodel',
            name='flags',
            field=models.SmallIntegerField(choices=[(0, '未付款'), (1, '已付款'), (2, '配送中'), (3, '已签收'), (4, '已取消'), (5, '退款中'), (6, '已退款')], default=0),
        ),
    ]
