# Generated by Django 3.0.3 on 2020-12-25 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20201225_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordershistorymodel',
            name='order',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='orders.OrderModel', verbose_name='关联订单'),
            preserve_default=False,
        ),
    ]
