# Generated by Django 3.0.3 on 2020-12-25 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_useraccountmodel_number'),
        ('orders', '0005_ordershistorymodel_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='tare',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='毛重'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.UserModel', verbose_name='关ƒ联用户'),
        ),
    ]
