# Generated by Django 3.0.3 on 2020-12-25 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_useraccountmodel_number'),
        ('orders', '0006_auto_20201225_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.UserModel', verbose_name='关联用户'),
        ),
    ]
