# Generated by Django 3.0.3 on 2020-12-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20201225_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordershistorymodel',
            name='serial_number',
            field=models.CharField(default='--------------------', max_length=255, verbose_name='订单编号'),
        ),
    ]
