# Generated by Django 3.0.3 on 2021-01-06 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_ordershistorymodel_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordershistorymodel',
            name='serial_number',
            field=models.CharField(max_length=255, verbose_name='订单编号'),
        ),
    ]
