# Generated by Django 3.1.2 on 2021-03-03 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0006_auto_20210301_1448'),
        ('orders', '0010_auto_20210301_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetailshistorymodel',
            name='productUnit',
        ),
        migrations.AlterField(
            model_name='orderdetailmodel',
            name='productUnit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.productunitmodel',
                                    verbose_name='关联产品SKU'),
        ),
    ]
