# Generated by Django 3.1.2 on 2021-03-03 02:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0011_auto_20210303_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetailmodel',
            name='productUnit',
        ),
    ]
