# Generated by Django 3.1.2 on 2021-03-08 08:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0012_remove_orderdetailmodel_productunit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetailmodel',
            old_name='purchase_price',
            new_name='price',
        ),
    ]
