# Generated by Django 3.1.2 on 2021-03-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0013_auto_20210308_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='credit',
            field=models.IntegerField(default=0, verbose_name='订单总积分'),
        ),
    ]
