# Generated by Django 3.0.3 on 2020-06-12 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccountsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'kh_user_accounts',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wx_open_id', models.CharField(max_length=255, verbose_name='微信openid')),
                ('wx_union_id', models.CharField(max_length=255, verbose_name='微信unionid')),
                ('wx_name', models.CharField(max_length=255, verbose_name='微信名')),
                ('wx_avatar_url', models.CharField(default='', max_length=255, verbose_name='头像')),
                ('mobile', models.CharField(blank=True, max_length=16, verbose_name='手机号')),
                ('name', models.CharField(max_length=16, null=True, verbose_name='用户的真实姓名')),
                ('gender', models.CharField(max_length=4, null=True, verbose_name='用户的真实性别')),
                ('phone', models.CharField(max_length=16, null=True, verbose_name='用户的联系电话')),
                ('email', models.CharField(max_length=255, null=True, verbose_name='用户的联系邮件')),
                ('address_id', models.IntegerField(null=True, verbose_name='默认地址id')),
                ('flags', models.SmallIntegerField(choices=[(0, '已申请'), (1, '待签协议'), (2, '已注册'), (3, '暂停')], verbose_name='用户状态')),
                ('logined_at', models.DateTimeField(auto_now_add=True, verbose_name='最后登录时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'kh_users',
            },
        ),
        migrations.CreateModel(
            name='UserLocationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='地图地址')),
                ('lat', models.FloatField(max_length=255, verbose_name='地图纬度')),
                ('lng', models.FloatField(max_length=255, verbose_name='地图经度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserModel', verbose_name='关联用户')),
            ],
            options={
                'db_table': 'kh_user_locations',
            },
        ),
        migrations.CreateModel(
            name='UserDocModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名称')),
                ('file_type', models.CharField(max_length=255, verbose_name='文件类型')),
                ('file_url', models.CharField(max_length=255, verbose_name='文件url')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserModel', verbose_name='关联用户')),
            ],
            options={
                'db_table': 'kh_user_docs',
            },
        ),
        migrations.CreateModel(
            name='UserBlacklistModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255, verbose_name='被暂停原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserModel', verbose_name='关联用户')),
            ],
            options={
                'db_table': 'kh_user_blacklist',
            },
        ),
        migrations.CreateModel(
            name='UserApplicationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='用户的真实姓名')),
                ('gender', models.CharField(max_length=4, verbose_name='用户的真实性别')),
                ('phone', models.CharField(max_length=16, verbose_name='用户的联系电话')),
                ('email', models.CharField(max_length=255, verbose_name='用户的联系邮件')),
                ('ip', models.GenericIPAddressField(db_index=True, protocol='ipv4', verbose_name='注册地IP地址')),
                ('idc_front_pic_url', models.CharField(max_length=255, verbose_name='证件照正面URL')),
                ('idc_back_pic_url', models.CharField(max_length=255, verbose_name='证件照背面URL')),
                ('reason_of_refusal', models.CharField(max_length=255, null=True, verbose_name='拒绝原因')),
                ('flags', models.SmallIntegerField(choices=[(0, '待审批'), (1, '同意'), (2, '不同意')], verbose_name='申请状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_applications', to='users.UserModel', verbose_name='关联用户')),
            ],
            options={
                'db_table': 'kh_user_applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAddressModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=16, verbose_name='收件人姓名')),
                ('contact_phone', models.CharField(max_length=16, verbose_name='收件人联系电话')),
                ('country', models.CharField(default='中国', max_length=255, verbose_name='收件人国籍')),
                ('province', models.CharField(max_length=255, verbose_name='收件人省份')),
                ('city', models.CharField(max_length=255, verbose_name='收件人城市')),
                ('address', models.CharField(max_length=255, verbose_name='收件人详细地址')),
                ('postcode', models.CharField(max_length=255, verbose_name='收件人邮编')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserModel', verbose_name='关联用户')),
            ],
            options={
                'db_table': 'kh_user_addresses',
            },
        ),
    ]
