# Generated by Django 3.0.3 on 2020-07-06 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccountsmodel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='useraccountsmodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='useraccountsmodel',
            name='phone',
        ),
        migrations.AddField(
            model_name='useraccountsmodel',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='单位元'),
        ),
        migrations.AddField(
            model_name='useraccountsmodel',
            name='flags',
            field=models.SmallIntegerField(choices=[(0, '支出'), (1, '收入')], default=0, verbose_name='账目类别'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccountsmodel',
            name='user',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='users.UserModel', verbose_name='关联用户'),
            preserve_default=False,
        ),
    ]
