# Generated by Django 3.0.3 on 2020-07-06 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200706_1505'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAccountsModel',
            new_name='UserAccountModel',
        ),
    ]
