# Generated by Django 3.0.3 on 2020-07-22 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0003_auto_20200706_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccountmodel',
            name='number',
            field=models.IntegerField(default=0, verbose_name='产品数量'),
        ),
        migrations.AddField(
            model_name='useraccountmodel',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.ProductModel', verbose_name='关联的产品'),
            preserve_default=False,
        ),
    ]
