# Generated by Django 3.0.3 on 2020-11-26 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200722_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='mobile',
        ),
    ]
