# Generated by Django 3.0.3 on 2020-11-29 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_usermodel_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccountmodel',
            name='product',
        ),
    ]
