# Generated by Django 3.0.3 on 2021-01-06 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_useraccountmodel_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='useraddressmodel',
            name='region',
            field=models.CharField(default='440113', max_length=16, verbose_name='地区编号'),
        ),
    ]
