# Generated by Django 3.0.3 on 2021-01-06 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210106_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddressmodel',
            name='district',
            field=models.CharField(default='', max_length=255, verbose_name='收件人地区'),
        ),
        migrations.AlterField(
            model_name='useraddressmodel',
            name='region',
            field=models.CharField(max_length=16, verbose_name='地区编号'),
        ),
    ]
