# Generated by Django 3.1.2 on 2021-03-09 02:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0011_auto_20210308_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='用户余额'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='credit',
            field=models.IntegerField(default=0, verbose_name='用户的积分'),
        ),
    ]
