# Generated by Django 3.1.2 on 2021-02-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0002_productunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='productunit',
            name='attributes',
            field=models.CharField(default='', max_length=255, verbose_name='单品规格'),
        ),
        migrations.AddField(
            model_name='productunit',
            name='description',
            field=models.CharField(default='', max_length=255, verbose_name='单品描述'),
        ),
    ]
