# Generated by Django 3.1.2 on 2021-02-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0003_auto_20210224_1559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productunit',
            options={'ordering': ['code']},
        ),
        migrations.AddField(
            model_name='productunit',
            name='code',
            field=models.CharField(default='', max_length=32, verbose_name='单品编号'),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='attributes',
            field=models.CharField(max_length=255, verbose_name='单品规格'),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='description',
            field=models.CharField(max_length=255, verbose_name='单品描述'),
        ),
    ]
