# Generated by Django 3.1.2 on 2021-02-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0004_auto_20210224_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productunit',
            name='pic_url',
        ),
        migrations.AlterField(
            model_name='productunit',
            name='code',
            field=models.CharField(max_length=32, verbose_name='单品编号'),
        ),
    ]
