# Generated by Django 3.1.2 on 2021-03-01 06:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0005_auto_20210225_1341'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductUnit',
            new_name='ProductUnitModel',
        ),
    ]
