# Generated by Django 3.1.2 on 2021-03-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0008_auto_20210308_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='point',
            field=models.IntegerField(default=0, verbose_name='单品积分'),
        ),
    ]
