# Generated by Django 3.0.3 on 2020-06-16 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intentions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intentiondetailsmodel',
            name='retail_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='交易单价元'),
        ),
    ]
