# Generated by Django 3.0.3 on 2020-11-26 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intentions', '0003_auto_20200706_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intentionsmodel',
            name='wx_mobile',
        ),
    ]
