# Generated by Django 3.0.3 on 2020-12-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intentions', '0005_intentionshistorymodel_intention'),
    ]

    operations = [
        migrations.AddField(
            model_name='intentionsmodel',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
    ]
