# Generated by Django 3.0.3 on 2020-12-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intentions', '0006_intentionsmodel_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='intentionshistorymodel',
            name='message',
            field=models.TextField(blank=True, verbose_name='客户留言'),
        ),
        migrations.AddField(
            model_name='intentionshistorymodel',
            name='quantity',
            field=models.SmallIntegerField(default=0, verbose_name='商品数量'),
        ),
        migrations.AddField(
            model_name='intentionshistorymodel',
            name='serial_number',
            field=models.CharField(default='LY00000000000000001', max_length=255, verbose_name='留言订单编号'),
        ),
        migrations.AddField(
            model_name='intentionshistorymodel',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AddField(
            model_name='intentionshistorymodel',
            name='wx_avatar_url',
            field=models.CharField(max_length=255, null=True, verbose_name='微信头像URL'),
        ),
        migrations.AddField(
            model_name='intentionshistorymodel',
            name='wx_union_id',
            field=models.CharField(default='a', max_length=255, verbose_name='微信unionid'),
        ),
        migrations.AlterField(
            model_name='intentionshistorymodel',
            name='address',
            field=models.CharField(max_length=255, verbose_name='客户详细地址'),
        ),
        migrations.AlterField(
            model_name='intentionshistorymodel',
            name='city',
            field=models.CharField(max_length=255, verbose_name='客户所在城市'),
        ),
        migrations.AlterField(
            model_name='intentionshistorymodel',
            name='country',
            field=models.CharField(default='中国', max_length=255, verbose_name='客户国籍'),
        ),
        migrations.AlterField(
            model_name='intentionshistorymodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='intentionshistorymodel',
            name='flags',
            field=models.SmallIntegerField(choices=[(0, '待分配'), (1, '已分配'), (2, '已完成'), (3, '已取消'), (4, '无法联系')], verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='intentionshistorymodel',
            name='name',
            field=models.CharField(max_length=16, verbose_name='客户姓名'),
        ),
        migrations.AlterField(
            model_name='intentionshistorymodel',
            name='phone',
            field=models.CharField(max_length=16, verbose_name='客户联系电话'),
        ),
        migrations.AlterField(
            model_name='intentionshistorymodel',
            name='postcode',
            field=models.CharField(max_length=255, verbose_name='客户地址的邮政编码'),
        ),
        migrations.AlterField(
            model_name='intentionshistorymodel',
            name='province',
            field=models.CharField(max_length=255, verbose_name='客户所在省份'),
        ),
        migrations.AlterField(
            model_name='intentionshistorymodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='intentionshistorymodel',
            name='wx_name',
            field=models.CharField(max_length=255, verbose_name='微信名'),
        ),
        migrations.AlterField(
            model_name='intentionshistorymodel',
            name='wx_open_id',
            field=models.CharField(max_length=255, verbose_name='微信openid'),
        ),
    ]
