# Generated by Django 3.0.3 on 2020-12-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intentions', '0007_auto_20201226_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intentionshistorymodel',
            name='serial_number',
            field=models.CharField(max_length=255, verbose_name='留言订单编号'),
        ),
        migrations.AlterField(
            model_name='intentionshistorymodel',
            name='wx_union_id',
            field=models.CharField(max_length=255, verbose_name='微信unionid'),
        ),
    ]
